/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.popup[_ngcontent-%COMP%] {\n  background-color: white;\n  border-radius: 10px;\n  color: #1688CB;\n  left: 0;\n  margin-left: auto;\n  margin-right: auto;\n  max-width: 375px;\n  padding: 0 20px 20px;\n  position: fixed;\n  right: 0;\n  top: 50%;\n  transform: translateY(-50%);\n  -webkit-transform: translateY(-50%);\n  width: 90%;\n}\nh2[_ngcontent-%COMP%], h3[_ngcontent-%COMP%] {\n  white-space: pre-wrap;\n}'];