/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../app/not-found.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from './common.css.shim';
export class Wrapper_NotFoundComponent {
  context:import0.NotFoundComponent;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.NotFoundComponent();
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_NotFoundComponent_Host:import2.RenderComponentType = (null as any);
class _View_NotFoundComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _NotFoundComponent_0_4:Wrapper_NotFoundComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_NotFoundComponent_Host0,renderType_NotFoundComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'not-found',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_NotFoundComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._NotFoundComponent_0_4 = new Wrapper_NotFoundComponent();
    this._appEl_0.initComponent(this._NotFoundComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._NotFoundComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.NotFoundComponent) && (0 === requestNodeIndex))) { return this._NotFoundComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NotFoundComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._NotFoundComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_NotFoundComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_NotFoundComponent_Host === (null as any))) { (renderType_NotFoundComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_NotFoundComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const NotFoundComponentNgFactory:import9.ComponentFactory<import0.NotFoundComponent> = new import9.ComponentFactory<import0.NotFoundComponent>('not-found',viewFactory_NotFoundComponent_Host0,import0.NotFoundComponent);
const styles_NotFoundComponent:any[] = [import10.styles];
var renderType_NotFoundComponent:import2.RenderComponentType = (null as any);
class _View_NotFoundComponent0 extends import1.AppView<import0.NotFoundComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_NotFoundComponent0,renderType_NotFoundComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_1 = import4.createRenderElement(this.renderer,parentRenderNode,'div',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'NOT FOUND',(null as any));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
}
export function viewFactory_NotFoundComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.NotFoundComponent> {
  if ((renderType_NotFoundComponent === (null as any))) { (renderType_NotFoundComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.Emulated,styles_NotFoundComponent,{})); }
  return new _View_NotFoundComponent0(viewUtils,parentInjector,declarationEl);
}