/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../app/submit.component';
import * as import1 from '@angular/core/src/change_detection/change_detection';
import * as import2 from '@angular/core/src/linker/view_utils';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/linker/element';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '../../app/app.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from './common.css.shim';
import * as import12 from './result.component.css.shim';
import * as import13 from '../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import14 from '@angular/router/src/router';
import * as import15 from '@angular/router/src/router_state';
import * as import16 from '@angular/common/src/location/location_strategy';
import * as import17 from '@angular/router/src/directives/router_link';
import * as import18 from '@angular/core/src/security';
export class Wrapper_SubmitComponent {
  context:import0.SubmitComponent;
  changed:boolean;
  /*private*/ _expr_0:any;
  constructor(p0:any) {
    this.changed = false;
    this.context = new import0.SubmitComponent(p0);
    this._expr_0 = import1.UNINITIALIZED;
  }
  check_result(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this.changed = true;
      this.context.result = currValue;
      this._expr_0 = currValue;
    }
  }
  detectChangesInInputProps(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  detectChangesInHostProps(view:import3.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_SubmitComponent_Host:import4.RenderComponentType = (null as any);
class _View_SubmitComponent_Host0 extends import3.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import5.AppElement;
  _SubmitComponent_0_4:Wrapper_SubmitComponent;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_SubmitComponent_Host0,renderType_SubmitComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = import2.selectOrCreateRenderHostElement(this.renderer,'submit',import2.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import5.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SubmitComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SubmitComponent_0_4 = new Wrapper_SubmitComponent(this.parentInjector.get(import8.AppService));
    this._appEl_0.initComponent(this._SubmitComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._SubmitComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.SubmitComponent) && (0 === requestNodeIndex))) { return this._SubmitComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._SubmitComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._SubmitComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SubmitComponent_Host0(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<any> {
  if ((renderType_SubmitComponent_Host === (null as any))) { (renderType_SubmitComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_SubmitComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const SubmitComponentNgFactory:import10.ComponentFactory<import0.SubmitComponent> = new import10.ComponentFactory<import0.SubmitComponent>('submit',viewFactory_SubmitComponent_Host0,import0.SubmitComponent);
const styles_SubmitComponent:any[] = [
  'img[_ngcontent-%COMP%] {\n		width: 96px;\n		height: 96px;\n		border-radius: 96px;\n	}',
  import11.styles,
  import12.styles
]
;
var renderType_SubmitComponent:import4.RenderComponentType = (null as any);
class _View_SubmitComponent0 extends import3.AppView<import0.SubmitComponent> {
  _text_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _RouterLinkWithHref_30_3:import13.Wrapper_RouterLinkWithHref;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_39:any;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_SubmitComponent0,renderType_SubmitComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
    this._expr_38 = import1.UNINITIALIZED;
    this._expr_39 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import5.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_3 = import2.createRenderElement(this.renderer,parentRenderNode,'div',new import2.InlineArray2(2,'class','content'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n	',(null as any));
    this._el_5 = import2.createRenderElement(this.renderer,this._el_3,'div',new import2.InlineArray2(2,'class','wheel center'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n		',(null as any));
    this._el_7 = import2.createRenderElement(this.renderer,this._el_5,'i',new import2.InlineArray2(2,'class','i-wheel'),(null as any));
    this._text_8 = this.renderer.createText(this._el_5,'\n		',(null as any));
    this._el_9 = import2.createRenderElement(this.renderer,this._el_5,'div',new import2.InlineArray2(2,'class','circle'),(null as any));
    this._text_10 = this.renderer.createText(this._el_5,'\n	',(null as any));
    this._text_11 = this.renderer.createText(this._el_3,'\n	',(null as any));
    this._el_12 = import2.createRenderElement(this.renderer,this._el_3,'div',new import2.InlineArray2(2,'class','white'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n		',(null as any));
    this._el_14 = import2.createRenderElement(this.renderer,this._el_12,'i',new import2.InlineArray2(2,'class','i-success center'),(null as any));
    this._text_15 = this.renderer.createText(this._el_12,'\n		',(null as any));
    this._el_16 = import2.createRenderElement(this.renderer,this._el_12,'div',import2.EMPTY_INLINE_ARRAY,(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'',(null as any));
    this._text_18 = this.renderer.createText(this._el_12,'\n		',(null as any));
    this._el_19 = import2.createRenderElement(this.renderer,this._el_12,'div',import2.EMPTY_INLINE_ARRAY,(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'\n			感谢参与，您的结果已经保存至浙江省矿业联合会官网中的上善若水计划板块中，您可以点击以下按钮链接进入矿联官网上善若水板块，进行查看您的成绩；',(null as any));
    this._el_21 = import2.createRenderElement(this.renderer,this._el_19,'br',import2.EMPTY_INLINE_ARRAY,(null as any));
    this._text_22 = this.renderer.createText(this._el_19,' 水是生命质量好坏的最基础的营养元素，好水“铸造”好体质，好的体内水环境有助与其他营养素的吸收、利用的效率，保持人体健康动态平衡。\n			',(null as any));
    this._el_23 = import2.createRenderElement(this.renderer,this._el_19,'br',import2.EMPTY_INLINE_ARRAY,(null as any));
    this._text_24 = this.renderer.createText(this._el_19,' 可能以自来水和净水器为主的这类解决您安全饮用的日常生活饮用水，已经不能满足拥有您这样健康饮水认知的人士群体，上善若水计划或许正好能满足您这样的健康饮水需求，为您提供亲民实惠的价格以及协助您养成科学健康的饮水习惯的互联网管家式服务；\n			',(null as any));
    this._el_25 = import2.createRenderElement(this.renderer,this._el_19,'br',import2.EMPTY_INLINE_ARRAY,(null as any));
    this._text_26 = this.renderer.createText(this._el_19,' 有兴趣不妨点击“了解一下 上善若水计划”。',(null as any));
    this._el_27 = import2.createRenderElement(this.renderer,this._el_19,'br',import2.EMPTY_INLINE_ARRAY,(null as any));
    this._text_28 = this.renderer.createText(this._el_19,'\n		',(null as any));
    this._text_29 = this.renderer.createText(this._el_12,'\n		',(null as any));
    this._el_30 = import2.createRenderElement(this.renderer,this._el_12,'a',new import2.InlineArray4(4,'class','button big blue center','routerLink','/rank'),(null as any));
    this._RouterLinkWithHref_30_3 = new import13.Wrapper_RouterLinkWithHref(this.parentInjector.get(import14.Router),this.parentInjector.get(import15.ActivatedRoute),this.parentInjector.get(import16.LocationStrategy));
    this._text_31 = this.renderer.createText(this._el_30,'进入官网 查看排名',(null as any));
    this._text_32 = this.renderer.createText(this._el_12,'\n		',(null as any));
    this._el_33 = import2.createRenderElement(this.renderer,this._el_12,'a',new import2.InlineArray2(2,'class','button big blue center'),(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'了解一下 上善若水计划',(null as any));
    this._text_35 = this.renderer.createText(this._el_12,'\n	',(null as any));
    this._text_36 = this.renderer.createText(this._el_3,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_30,'click',this.eventHandler(this._handle_click_30_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_33,'click',this.eventHandler(this._handle_click_33_0.bind(this)));
    this.init(([] as any[]),[
      this._text_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._text_36
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.RouterLinkWithHref) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._RouterLinkWithHref_30_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_30_0_0:any = '/rank';
    this._RouterLinkWithHref_30_3.check_routerLink(currVal_30_0_0,throwOnChange,false);
    this._RouterLinkWithHref_30_3.detectChangesInInputProps(this,this._el_30,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_38:any = (('url(' + this.context.appService.user.headImgUrl) + ')');
    if (import2.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementStyle(this._el_9,'backgroundImage',((this.viewUtils.sanitizer.sanitize(import18.SecurityContext.STYLE,currVal_38) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import18.SecurityContext.STYLE,currVal_38).toString()));
      this._expr_38 = currVal_38;
    }
    const currVal_39:any = import2.interpolate(1,'',(this.context.appService.user.realName || this.context.appService.user.nickName),'');
    if (import2.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setText(this._text_17,currVal_39);
      this._expr_39 = currVal_39;
    }
    this._RouterLinkWithHref_30_3.detectChangesInHostProps(this,this._el_30,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_30_3.context.ngOnDestroy();
  }
  private _handle_click_30_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_30_0:any = ((<any>this._RouterLinkWithHref_30_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_30_0);
  }
  private _handle_click_33_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_33_0:any = ((<any>this.context.appService.goExternal()) !== false);
    return (true && pd_33_0);
  }
}
export function viewFactory_SubmitComponent0(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<import0.SubmitComponent> {
  if ((renderType_SubmitComponent === (null as any))) { (renderType_SubmitComponent = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.Emulated,styles_SubmitComponent,{})); }
  return new _View_SubmitComponent0(viewUtils,parentInjector,declarationEl);
}